default_node_image: &default_node_image
  docker:
    - image: circleci/node:9-browsers

aliases:
  - &restore_cache
    restore_cache:
      keys:
        - node-dependencies-{{ checksum "package.json" }}
  - &start_mockserver
    run:
      command: npm run test:mockserver
      background: true
  - &build_and_start_app
    run:
      command: npm start > build.log
      background: true
  - &wait_for_app_to_start
    run:
      name: Pause until server is ready to serve
      command: while ! grep "Compiled successfully!" build.log; do echo waiting; sleep 1; done
  - &install_latest_chrome
    run:
      name: Install Chromedriver latest version
      command: |
        sudo apt-get update
        sudo apt-get install lsb-release libappindicator3-1
        curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome.deb
        sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
        rm google-chrome.deb

version: 2
jobs:
  dependencies:
    <<: *default_node_image
    steps:
      - checkout
      - *restore_cache
      - run:
          command: npm install
      - save_cache:
          name: Save cache
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  unit_tests:
    <<: *default_node_image
    steps:
      - checkout
      - *restore_cache
      - run: npm test

  browser_tests:
    <<: *default_node_image
    steps:
      - checkout
      - *restore_cache
      - *start_mockserver
      - *build_and_start_app
      - *wait_for_app_to_start
      - *install_latest_chrome
      - run:
          name: Run Browser Tests
          command: npm run test:browser

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies
      - unit_tests:
          requires:
            - dependencies
      - browser_tests:
          requires:
            - dependencies
